name: Auto Release Package

on:
  push:
    branches:
      - main
    paths:
      - DESCRIPTION

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch full history for tagging

      - name: Configure Git
        run: |
          git config --global user.email "lichenyu6020@outlook.com"
          git config --global user.name "chenyu-psy"

      - name: Get Version from DESCRIPTION
        id: get_version
        run: |
          VERSION=$(grep '^Version:' DESCRIPTION | awk '{print $2}')
          echo "PACKAGE_VERSION=$VERSION" >> $GITHUB_ENV
          echo "Detected version: $VERSION"

      - name: Delete existing tag if it exists
        run: |
          git tag -d v${{ env.PACKAGE_VERSION }} || true
          git push --delete origin v${{ env.PACKAGE_VERSION }} || true

      - name: Create and Push Git Tag
        run: |
          git tag -a v${{ env.PACKAGE_VERSION }} -m "Release version ${{ env.PACKAGE_VERSION }}"
          git push origin v${{ env.PACKAGE_VERSION }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ env.PACKAGE_VERSION }}
          release_name: "Version ${{ env.PACKAGE_VERSION }}"
          body: "This is an automated release for version ${{ env.PACKAGE_VERSION }}."
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
